descriptor_extension: yml
package:
  description: ETSI Plugtest Alpha Networks and nt4g
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-alpha-nt4g"
  vendor: "eu.sonata"
  version: "0.5"
version: '0.5'
