descriptor_extension: yml
package:
  description: ETSI Plugtest Fortios + IT Aveiro
  maintainer: Thomas Soenen - Ugent / imec
  name: "fortios-itaveiro"
  vendor: "fortios-itaveiro"
  version: "0.1"
version: "0.5"
