descriptor_extension: yml
package:
  description: ETSI Plugtest A10NETWORKS
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-a10networks"
  vendor: "a10networks"
  version: "0.5"
version: '0.5'
