descriptor_extension: yml
package:
  description: ETSI Plugtest Eurecom OAI
  maintainer: Carlos Parada, Altice Labs, carlos-f-parada@alticelabs.com
  name: "etsi-eurecom"
  vendor: "eurecom"
  version: "0.1"
version: "0.5"
