descriptor_extension: yml
package:
  description: ETSI Plugtest NG4T-Eurecom-NG4T
  maintainer: Carlos Parada, Altice Labs, carlos-f-parada@alticelabs.com
  name: "etsi-ng4t_ran-eurecom_epc-ng4t_hss"
  vendor: "ng4t_ran-eurecom_epc-ng4t_hss"
  version: "0.1"
version: "0.5"
