descriptor_extension: yml
package:
  description: ETSI Plugtest EMPIRIX
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-empirix"
  vendor: "empirix"
  version: "0.5"
version: '0.5'
