descriptor_extension: yml
package:
  description: ETSI Plugtest Fortios
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-fortios"
  vendor: "fortios"
  version: "0.5"
version: '0.5'
